site_name: "*notes"
site_description: Technical knowledge base and documentation
docs_dir: docs
theme:
  name: material
  palette:
  - scheme: slate
    primary: amber
    accent: red
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: default
    primary: black
    accent: red
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
#  - navigation.path
  - search.highlight
  - search.suggest
  - content.code.copy
  - content.code.annotate
nav:
- Home: index.md
- Linux:
  - Overview: linux/index.md
  - Bash: linux/bash/operators/index.md
  - Tools: linux/rust-tools/rust-tools.md
#  - Команды: linux/commands/index.md
#  - Установка: linux/installation/index.md
  - Сети:
    - Trojan-proxy: linux/networking/trojan-proxy/index.md
  - firewall: linux/networking/firewall/index.md
  - uwfdocker: linux/networking/firewall_docker/index.md
  - Draft:
#    - OpenSuse16+Docker+WGeasy: linux/draft/sudockerwg/index.md
    - Suse+WG: linux/draft/suwg/index.md
  
#- LAN: lan/index.md
- Docker:
  - Обзор: Docker/overview/index.md
  - Команды: Docker/commands/index.md
  - Установка: Docker/setup/index.md
  - Создание и запуск контейнера: Docker/container/index.md
  - Оптимизация и настройка образа: Docker/image_optimization/index.md
  - Файловая система: Docker/filesystem/index.md
  - Сети: Docker/networking/index.md
  - Безопасность: Docker/security/index.md
  - Docker Compose: Docker/compose/index.md
- Ansible:
  - Установка: ansible/setup/index.md
  - Конфигурация: ansible/config/index.md
#  - Базовые ad-hoc комманды: ansible/base/index.md
  - Ad-hoc: ansible/ad-hoc/index.md
  - Callback: ansible/callback/index.md
  - Playbooks: ansible/playbooks/index.md
  - Vault: ansible/vault/index.md
  - Galaxy: ansible/galaxy/index.md
  - Lint: ansible/ansible-lint/index.md
  - Environment: ansible/env/index.md
  - HA PostgreSQL : ansible/ha-postgres/index.md
- Kubernetes:
  - Commands Reference: kubernetes/commands-reference/index.md
  - WorkLoads: kubernetes/workloads/index.md
  - Qos resources: kubernetes/qos/index.md
  - Network-ingress: kubernetes/network-ingress/index.md
  - Config Storage: kubernetes/config-storage/kubernetes-config-storage.md
  - RBAC & Network Policies: kubernetes/rbac-network/index.md
  - HELM: kubernetes/helm.md
  - CRD and Operators: kubernetes/CRD-and-Operators.md
  - Helmfile and templating: kubernetes/Helmfile-and-templating.md
  - SOPS and secret encryption: kubernetes/SOPS-and-secret-encryption.md
  - Node Scheduling: kubernetes/scheduling/node-scheduling.md
  - CLI Tools:
    - kubectl basics: kubernetes/cli-tools/kubectl-basics.md
    - kubectl workloads: kubernetes/cli-tools/kubectl-workloads.md
    - kubectl config: kubernetes/cli-tools/kubectl-config.md
    - kubectl networking: kubernetes/cli-tools/kubectl-networking.md
    - kubectl storage: kubernetes/cli-tools/kubectl-storage.md
    - kubectl rbac: kubernetes/cli-tools/kubectl-rbac.md
    - kubectl advanced: kubernetes/cli-tools/kubectl-advanced.md
    - kubeadm: kubernetes/cli-tools/kubeadm.md
    - kubelet: kubernetes/cli-tools/kubelet.md
    - helm: kubernetes/cli-tools/helm.md
    - etcdctl: kubernetes/cli-tools/etcdctl.md
    - crictl: kubernetes/cli-tools/crictl.md
- Terraform:
  - Overview: terraform/index.md
#  - Basics: terraform/basics/index.md
  - Syntax: terraform/syntax/index.md
  - Lab:
     -lab1: terraform/lab/lab1.md
     -lab2: terraform/lab/lab2.md
     -lab3: terraform/lab/lab3.md
     -lab4: terraform/lab/lab4.md
     -yandex: terraform/lab/yandex.md
     -git: terraform/lab/git.md
     -GitLab CI/CD: terraform/lab/gitlab_cicd.md
#  - Аутентификация: security/authentication/index.md
#  - Шифрование: security/encryption/index.md
#  - Защита: security/hardening/index.md
- Monitoring:
  - Monitoring Stack:
    - Setup:  monitoring/monitoring-stack/setup.md
    - Prometheus metrics: monitoring/monitoring-stack/metrics.md
    - Loki logs: monitoring/monitoring-stack/logs.md
    - Alerting conf: monitoring/monitoring-stack/alerts.md
    - Grafana dashboards: monitoring/monitoring-stack/dashboards.md
    - Summary: monitoring/monitoring-stack/final.md 
- IaC:
  - Infrastructure Setup: kubernetes/infrastructure-setup-full.md
  - Infrastructure Prep: iac/infrastructure-prep.md
  - Automation and Fixes: iac/k8s-cluster-automation.md
  - Deployment approaches: iac/k8s-deployment-approaches.md 
- DataBases:
  - Patroni + etcd + PostgreSQL HA: databases/postgresha/index.md
plugins:
- search
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    auto_title: true
    line_spans: true
- attr_list
extra_css:
#- https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css
- assets/stylesheets/extra.css
extra_javascript:
- assets/javascripts/terminal.js:
